package yahoo

// mockplayers.go holds the static player pool backing mock mode.
//
// Generated once from the top ~200 players by 2026 projected PPR points, so
// mock rosters read like a plausible draft rather than random names. It is
// committed as a literal on purpose: package yahoo has no database access,
// and mock mode must work against an empty database.
//
// This is fixture data, not a source of truth — nothing reads it outside
// mock mode, and it is never written back anywhere.

var mockPlayerPool = []mockPlayer{
	{name: "Puka Nacua", pos: "WR", team: "LA"},
	{name: "Josh Allen", pos: "QB", team: "BUF"},
	{name: "Bijan Robinson", pos: "RB", team: "ATL"},
	{name: "Jahmyr Gibbs", pos: "RB", team: "DET"},
	{name: "Drake Maye", pos: "QB", team: "NE"},
	{name: "Ja'Marr Chase", pos: "WR", team: "CIN"},
	{name: "Jaxson Dart", pos: "QB", team: "NYG"},
	{name: "De'Von Achane", pos: "RB", team: "MIA"},
	{name: "Lamar Jackson", pos: "QB", team: "BAL"},
	{name: "Joe Burrow", pos: "QB", team: "CIN"},
	{name: "Christian McCaffrey", pos: "RB", team: "SF"},
	{name: "Patrick Mahomes", pos: "QB", team: "KC"},
	{name: "Trevor Lawrence", pos: "QB", team: "JAX"},
	{name: "Brock Purdy", pos: "QB", team: "SF"},
	{name: "Jonathan Taylor", pos: "RB", team: "IND"},
	{name: "Jaxon Smith-Njigba", pos: "WR", team: "SEA"},
	{name: "Amon-Ra St. Brown", pos: "WR", team: "DET"},
	{name: "Jalen Hurts", pos: "QB", team: "PHI"},
	{name: "Jayden Daniels", pos: "QB", team: "WAS"},
	{name: "Dak Prescott", pos: "QB", team: "DAL"},
	{name: "Baker Mayfield", pos: "QB", team: "TB"},
	{name: "Jared Goff", pos: "QB", team: "DET"},
	{name: "Malik Nabers", pos: "WR", team: "NYG"},
	{name: "Bo Nix", pos: "QB", team: "DEN"},
	{name: "Cam Skattebo", pos: "RB", team: "NYG"},
	{name: "Rashee Rice", pos: "WR", team: "KC"},
	{name: "Brock Bowers", pos: "TE", team: "LV"},
	{name: "Caleb Williams", pos: "QB", team: "CHI"},
	{name: "Kyler Murray", pos: "QB", team: "ARI"},
	{name: "Chase Brown", pos: "RB", team: "CIN"},
	{name: "Justin Herbert", pos: "QB", team: "LAC"},
	{name: "Kyren Williams", pos: "RB", team: "LA"},
	{name: "Daniel Jones", pos: "QB", team: "IND"},
	{name: "Drake London", pos: "WR", team: "ATL"},
	{name: "Ashton Jeanty", pos: "RB", team: "LV"},
	{name: "Trey McBride", pos: "TE", team: "ARI"},
	{name: "Omarion Hampton", pos: "RB", team: "LAC"},
	{name: "CeeDee Lamb", pos: "WR", team: "DAL"},
	{name: "Jacoby Brissett", pos: "QB", team: "ARI"},
	{name: "George Pickens", pos: "WR", team: "DAL"},
	{name: "Matthew Stafford", pos: "QB", team: "LA"},
	{name: "Chris Olave", pos: "WR", team: "NO"},
	{name: "James Cook", pos: "RB", team: "BUF"},
	{name: "Nico Collins", pos: "WR", team: "HOU"},
	{name: "Jordan Love", pos: "QB", team: "GB"},
	{name: "Sam Darnold", pos: "QB", team: "SEA"},
	{name: "Tee Higgins", pos: "WR", team: "CIN"},
	{name: "Tyler Shough", pos: "QB", team: "NO"},
	{name: "A.J. Brown", pos: "WR", team: "PHI"},
	{name: "Derrick Henry", pos: "RB", team: "BAL"},
	{name: "Saquon Barkley", pos: "RB", team: "PHI"},
	{name: "Tetairoa McMillan", pos: "WR", team: "CAR"},
	{name: "Carson Wentz", pos: "QB", team: "MIN"},
	{name: "C.J. Stroud", pos: "QB", team: "HOU"},
	{name: "Zay Flowers", pos: "WR", team: "BAL"},
	{name: "Josh Jacobs", pos: "RB", team: "GB"},
	{name: "Garrett Wilson", pos: "WR", team: "NYJ"},
	{name: "Bucky Irving", pos: "RB", team: "TB"},
	{name: "Breece Hall", pos: "RB", team: "NYJ"},
	{name: "Javonte Williams", pos: "RB", team: "DAL"},
	{name: "Justin Jefferson", pos: "WR", team: "MIN"},
	{name: "Harold Fannin Jr.", pos: "TE", team: "CLE"},
	{name: "George Kittle", pos: "TE", team: "SF"},
	{name: "Jameson Williams", pos: "WR", team: "DET"},
	{name: "Tyler Warren", pos: "TE", team: "IND"},
	{name: "Kenneth Walker III", pos: "RB", team: "SEA"},
	{name: "Mac Jones", pos: "QB", team: "SF"},
	{name: "Bryce Young", pos: "QB", team: "CAR"},
	{name: "Justin Fields", pos: "QB", team: "NYJ"},
	{name: "DK Metcalf", pos: "WR", team: "PIT"},
	{name: "DeVonta Smith", pos: "WR", team: "PHI"},
	{name: "Tua Tagovailoa", pos: "QB", team: "MIA"},
	{name: "RJ Harvey", pos: "RB", team: "DEN"},
	{name: "Aaron Rodgers", pos: "QB", team: "PIT"},
	{name: "Davante Adams", pos: "WR", team: "LA"},
	{name: "Brian Thomas Jr.", pos: "WR", team: "JAX"},
	{name: "Cam Ward", pos: "QB", team: "TEN"},
	{name: "Quinshon Judkins", pos: "RB", team: "CLE"},
	{name: "Michael Penix Jr.", pos: "QB", team: "ATL"},
	{name: "Wan'Dale Robinson", pos: "WR", team: "NYG"},
	{name: "Quentin Johnston", pos: "WR", team: "LAC"},
	{name: "Ladd McConkey", pos: "WR", team: "LAC"},
	{name: "Emeka Egbuka", pos: "WR", team: "TB"},
	{name: "Jaylen Waddle", pos: "WR", team: "MIA"},
	{name: "Travis Etienne", pos: "RB", team: "JAX"},
	{name: "D'Andre Swift", pos: "RB", team: "CHI"},
	{name: "Jauan Jennings", pos: "WR", team: "SF"},
	{name: "Dallas Goedert", pos: "TE", team: "PHI"},
	{name: "Geno Smith", pos: "QB", team: "LV"},
	{name: "Marcus Mariota", pos: "QB", team: "WAS"},
	{name: "Colston Loveland", pos: "TE", team: "CHI"},
	{name: "Khalil Shakir", pos: "WR", team: "BUF"},
	{name: "Luther Burden III", pos: "WR", team: "CHI"},
	{name: "J.J. McCarthy", pos: "QB", team: "MIN"},
	{name: "Chris Godwin Jr.", pos: "WR", team: "TB"},
	{name: "TreVeyon Henderson", pos: "RB", team: "NE"},
	{name: "Alec Pierce", pos: "WR", team: "IND"},
	{name: "Davis Mills", pos: "QB", team: "HOU"},
	{name: "DJ Moore", pos: "WR", team: "CHI"},
	{name: "Sam LaPorta", pos: "TE", team: "DET"},
	{name: "Jakobi Meyers", pos: "WR", team: "JAX"},
	{name: "Zach Charbonnet", pos: "RB", team: "SEA"},
	{name: "Parker Washington", pos: "WR", team: "JAX"},
	{name: "Spencer Rattler", pos: "QB", team: "NO"},
	{name: "Michael Wilson", pos: "WR", team: "ARI"},
	{name: "Deebo Samuel Sr.", pos: "WR", team: "WAS"},
	{name: "Jordan Addison", pos: "WR", team: "MIN"},
	{name: "Bam Knight", pos: "RB", team: "ARI"},
	{name: "Rico Dowdle", pos: "RB", team: "CAR"},
	{name: "J.K. Dobbins", pos: "RB", team: "DEN"},
	{name: "Travis Hunter", pos: "WR", team: "JAX"},
	{name: "Marvin Harrison Jr.", pos: "WR", team: "ARI"},
	{name: "Michael Pittman", pos: "WR", team: "IND"},
	{name: "Jaylen Warren", pos: "RB", team: "PIT"},
	{name: "Tucker Kraft", pos: "TE", team: "GB"},
	{name: "Courtland Sutton", pos: "WR", team: "DEN"},
	{name: "Terry McLaurin", pos: "WR", team: "WAS"},
	{name: "Malik Willis", pos: "QB", team: "GB"},
	{name: "Mike Evans", pos: "WR", team: "TB"},
	{name: "Tyreek Hill", pos: "WR", team: "MIA"},
	{name: "Xavier Worthy", pos: "WR", team: "KC"},
	{name: "Tony Pollard", pos: "RB", team: "TEN"},
	{name: "Travis Kelce", pos: "TE", team: "KC"},
	{name: "Oronde Gadsden II", pos: "TE", team: "LAC"},
	{name: "Christian Watson", pos: "WR", team: "GB"},
	{name: "Jayden Reed", pos: "WR", team: "GB"},
	{name: "Shedeur Sanders", pos: "QB", team: "CLE"},
	{name: "Tyler Huntley", pos: "QB", team: "BAL"},
	{name: "Rome Odunze", pos: "WR", team: "CHI"},
	{name: "Stefon Diggs", pos: "WR", team: "NE"},
	{name: "Rhamondre Stevenson", pos: "RB", team: "NE"},
	{name: "Jake Ferguson", pos: "TE", team: "DAL"},
	{name: "Woody Marks", pos: "RB", team: "HOU"},
	{name: "Tyjae Spears", pos: "RB", team: "TEN"},
	{name: "Keon Coleman", pos: "WR", team: "BUF"},
	{name: "Josh Downs", pos: "WR", team: "IND"},
	{name: "David Montgomery", pos: "RB", team: "DET"},
	{name: "Alvin Kamara", pos: "RB", team: "NO"},
	{name: "Dillon Gabriel", pos: "QB", team: "CLE"},
	{name: "Romeo Doubs", pos: "WR", team: "GB"},
	{name: "Chuba Hubbard", pos: "RB", team: "CAR"},
	{name: "Troy Franklin", pos: "WR", team: "DEN"},
	{name: "Jake Tonges", pos: "TE", team: "SF"},
	{name: "Kyle Pitts", pos: "TE", team: "ATL"},
	{name: "Ricky Pearsall", pos: "WR", team: "SF"},
	{name: "Jake Browning", pos: "QB", team: "CIN"},
	{name: "Tyrone Tracy Jr.", pos: "RB", team: "NYG"},
	{name: "Hunter Henry", pos: "TE", team: "NE"},
	{name: "Juwan Johnson", pos: "TE", team: "NO"},
	{name: "Dalton Kincaid", pos: "TE", team: "BUF"},
	{name: "Kenneth Gainwell", pos: "RB", team: "PIT"},
	{name: "David Njoku", pos: "TE", team: "CLE"},
	{name: "Aaron Jones", pos: "RB", team: "MIN"},
	{name: "Jalen McMillan", pos: "WR", team: "TB"},
	{name: "Russell Wilson", pos: "QB", team: "NYG"},
	{name: "Zach Ertz", pos: "TE", team: "WAS"},
	{name: "Rachaad White", pos: "RB", team: "TB"},
	{name: "Darren Waller", pos: "TE", team: "MIA"},
	{name: "AJ Barner", pos: "TE", team: "SEA"},
	{name: "Jerry Jeudy", pos: "WR", team: "CLE"},
	{name: "Tory Horton", pos: "WR", team: "SEA"},
	{name: "Kimani Vidal", pos: "RB", team: "LAC"},
	{name: "Kyle Monangai", pos: "RB", team: "CHI"},
	{name: "Rashid Shaheed", pos: "WR", team: "SEA"},
	{name: "Kayshon Boutte", pos: "WR", team: "NE"},
	{name: "Tre Tucker", pos: "WR", team: "LV"},
	{name: "Dalton Schultz", pos: "TE", team: "HOU"},
	{name: "Elic Ayomanor", pos: "WR", team: "TEN"},
	{name: "Jacory Croskey-Merritt", pos: "RB", team: "WAS"},
	{name: "Keenan Allen", pos: "WR", team: "LAC"},
	{name: "Cade Otton", pos: "TE", team: "TB"},
	{name: "Tyrod Taylor", pos: "QB", team: "NYJ"},
	{name: "Kirk Cousins", pos: "QB", team: "ATL"},
	{name: "Chimere Dike", pos: "WR", team: "TEN"},
	{name: "Jalen Coker", pos: "WR", team: "CAR"},
	{name: "Mark Andrews", pos: "TE", team: "BAL"},
	{name: "Marquise Brown", pos: "WR", team: "KC"},
	{name: "Theo Johnson", pos: "TE", team: "NYG"},
	{name: "Brenton Strange", pos: "TE", team: "JAX"},
	{name: "Justice Hill", pos: "RB", team: "BAL"},
	{name: "Mason Taylor", pos: "TE", team: "NYJ"},
	{name: "Quinn Ewers", pos: "QB", team: "MIA"},
	{name: "Kareem Hunt", pos: "RB", team: "KC"},
	{name: "Pat Freiermuth", pos: "TE", team: "PIT"},
	{name: "Devontez Walker", pos: "WR", team: "BAL"},
	{name: "Jayden Higgins", pos: "WR", team: "HOU"},
	{name: "Joe Flacco", pos: "QB", team: "CIN"},
	{name: "Sean Tucker", pos: "RB", team: "TB"},
	{name: "Darnell Mooney", pos: "WR", team: "ATL"},
	{name: "Ryan Flournoy", pos: "WR", team: "DAL"},
	{name: "Devaughn Vele", pos: "WR", team: "NO"},
	{name: "T.J. Hockenson", pos: "TE", team: "MIN"},
	{name: "Jordan Mason", pos: "RB", team: "MIN"},
	{name: "Colby Parkinson", pos: "TE", team: "LA"},
	{name: "Calvin Ridley", pos: "WR", team: "TEN"},
	{name: "Isaiah Williams", pos: "WR", team: "NYJ"},
	{name: "Tyler Allgeier", pos: "RB", team: "ATL"},
	{name: "DeMario Douglas", pos: "WR", team: "NE"},
	{name: "Chig Okonkwo", pos: "TE", team: "TEN"},
	{name: "Dylan Sampson", pos: "RB", team: "CLE"},
	{name: "Audric Estimé", pos: "RB", team: "NO"},
	{name: "Marvin Mims Jr.", pos: "WR", team: "DEN"},
	{name: "Evan Engram", pos: "TE", team: "DEN"},
	{name: "Michael Carter", pos: "RB", team: "ARI"},
	{name: "Tyquan Thornton", pos: "WR", team: "KC"},
	{name: "Devin Neal", pos: "RB", team: "NO"},
	{name: "Cooper Kupp", pos: "WR", team: "SEA"},
	{name: "Tyler Higbee", pos: "TE", team: "LA"},
	{name: "Tez Johnson", pos: "WR", team: "TB"},
	{name: "Malik Washington", pos: "WR", team: "MIA"},
}
